Role Welcome UI
CigarLounge/sbox-TTT pull request #304
Opened 2023-01-12 20:11 UTC by Ephememory

https://cdn.discordapp.com/attachments/1057060299947114498/1063169693399130172/text.png

2023-01-12 20:13 UTC, matekdev commented
we chatted about this i'll have a PR up with some of these changes

2023-01-12 23:19 UTC, matekdev commented
Solves https://github.com/CigarLounge/sbox-TTT/issues/178

2023-01-12 23:23 UTC, kolexxx requested changes

2023-01-12 23:23 UTC, kolexxx commented on code/Events/Event.Roles.cs
> +}
Why is this needed? We should be using `GameEvent.Round.Start`.

2023-01-12 23:23 UTC, kolexxx commented on code/Util/NetworkedEvent.cs
> +public static partial class NetworkedEvent
This is not needed.

2023-01-13 04:54 UTC, matekdev commented
I'll branch off of this and finish up the rest, thanks.

2023-01-13 04:54 UTC, closed without merging